### ISSUE TITLE
[FEATURE] Add test for #36

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/demos#39]
### Is your feature request related to a problem?
We added the ability to read from the `data` directory in #36

### What solution would you like?
We need to add a related test to ensure that we have test coverage for it. The tests should ensure that if the directory is empty the appropriate directory is returned.

**Comment by LucasWang750** [comment]
Can I please take this issue.

**Comment by dtaivpp** [comment]
@LucasWang750  here is how I would probably recommend going about testing this. 

1. Change the original function to take in a path with the default value set to the environment variable we created. 
2. Then you can test that the function returns data in the correct format (eg, isinstance(returned data, dict))
3. Then we can create assertions when we pass in an empty directory (`/dev/null` on linux/unix systems should work) that the appropriate error is raised

**Comment by dtaivpp** [comment]
Closed with #47
