### ISSUE TITLE
[FEATURE] DocBot Cluster Settings Bootstrapping

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/demos#40]
### What solution would you like?
Before we run anything we need to ensure the cluster is setup appropriately. This will involve running a cluster bootstrapping script. This script should validate the cluster settings match what our expected settings are. 

- Enable ML commons and settings ([see this gist](https://gist.github.com/dtaivpp/9d2a458e59cf94ba803e99c4d8b140ec))
- [Enable RAG](https://opensearch.org/docs/latest/ml-commons-plugin/conversational-search#enabling-rag)

Ideally we should use an auto-executing import for this. This is something like the following: 
```python
# ingestion.py
import bootstrapping
```

```python
# bootstrapping.py

def function_to_validate_cluster_is_ready()
    some checks and steps

# call the function at the end to ensure the cluster is bootstrapped. 
function_to_validate_cluster_is_ready()
```

**Comment by miriamcheng** [comment]
Mekaeel and Miriam would also like to contribute code to this part!

**Comment by dtaivpp** [comment]
completed!
