### ISSUE TITLE
[FEATURE] Add environment defaults

### ISSUE THREAD

**Issue by mekaeelahmad** [opensearch-project/demos#41]
### Is your feature request related to a problem?
When setting up the application, users are currently bound to using a '.env' environment for configurations. This might not be convenient for all users, especially for this who may prefer passing configurations directly or using defaults. 

### What solution would you like?
I propose allowing users to pass in "use_ssl" settings directly. We can also utilize 'getenv' to create defaults. In cases where users have a '.env' environment file, these settings would override the defaults which would provide more flexibility.

### What alternatives have you considered?
Keeping the current setup: This would mean that users are bound to using the '.env' environment file. While it does work, adding more configuration would be nice!

**Comment by dtaivpp** [comment]
@mekaeelahmad sounds great! Assigned you here :D

**Comment by dtaivpp** [comment]
completed!
