### ISSUE TITLE
[FEATURE] Add parameter expansion to docker-compose.yml

### ISSUE THREAD

**Issue by ortegaa32** [opensearch-project/demos#49]
### Is your feature request related to a problem?
Currently, running `docker-compose up -d` leads to a couple warnings and errors if the OpenSearch/OpenSearch-Dashboards version doesn't exist in the user's shell

### What solution would you like?
We can use parameter expansion to say if the relevant environment variables aren't set, to use a default.

**Comment by ortegaa32** [comment]
I'd like to work on this issue

**Comment by dtaivpp** [comment]
Closed with #51 Thank you!
