### ISSUE TITLE
[FEATURE][docbot] Import API Keys for Cohere

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/demos#52]
### Is your feature request related to a problem?
In our `cluster_bootstrap.py` we need to have an environment variable imported with our Cohere api key. 

### What solution would you like?
There should be an import like in `util.py` to get the cohere environment variable. 

https://github.com/opensearch-project/demos/blob/db2b22e5c3f4bab03a3e3436ecc0c0211263e142/demo/docbot/util.py#L1

### Do you have any additional context?
#40

**Comment by RobertKilkenny** [comment]
I would like to work on this!

**Comment by dtaivpp** [comment]
no

**Comment by dtaivpp** [comment]
Completed
