### ISSUE TITLE
[BUG][DocBot] Using object comparsion fails, need to compare parameters

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/demos#63]
### What is the bug?
In the following sections we do object comparison to see if the settings we expect match the current settings. These will fail as object comparison only looks at if the objects in memory are the same object not if their parameters match. We should create a utility or use some existing library for deep object inspection. 

This function can live in the `util.py` if we end up implementing ourselves. 

- https://github.com/opensearch-project/demos/blob/9e93460a2dfd577d91777d5da9f306bae92504eb/demo/docbot/cluster_bootstrap.py#L35
- https://github.com/opensearch-project/demos/blob/9e93460a2dfd577d91777d5da9f306bae92504eb/demo/docbot/cluster_bootstrap.py#L92
- https://github.com/opensearch-project/demos/blob/9e93460a2dfd577d91777d5da9f306bae92504eb/demo/docbot/cluster_bootstrap.py#L138
- https://github.com/opensearch-project/demos/blob/9e93460a2dfd577d91777d5da9f306bae92504eb/demo/docbot/cluster_bootstrap.py#L163
- https://github.com/opensearch-project/demos/blob/9e93460a2dfd577d91777d5da9f306bae92504eb/demo/docbot/cluster_bootstrap.py#L196
- https://github.com/opensearch-project/demos/blob/9e93460a2dfd577d91777d5da9f306bae92504eb/demo/docbot/cluster_bootstrap.py#L239

**Comment by yash1506** [comment]
I would like to work on this!

**Comment by dtaivpp** [comment]
@yash1506 assigned!

**Comment by miriamcheng** [comment]
Mekaeel and I also wrote some code to contribute!

**Comment by dtaivpp** [comment]
Closed! Thanks for all the hard work on this one
