### ISSUE TITLE
[BUG][DocBot] Need exceptions in custer_bootstrap.py

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/demos#64]
### What is the bug?
In our `cluster_bootstrap.py` we should be raising the appropriate exceptions instead of printing errors when we come across them. Additionally we will need to wrap the main block in a try except to handle those accordingly.
https://github.com/opensearch-project/demos/pull/60/files#r1368888960

### What is the expected behavior?
Anytime a function fails we expect it to raise an exception rather than silently failing. 

### Do you have any additional context?
N/A

**Comment by LucasWang750** [comment]
I would like to work on this issue

**Comment by dtaivpp** [comment]
Closed with #70
