### ISSUE TITLE
[FEATURE][DocBot] Enable conversational search and RAG in cluster

### ISSUE THREAD

**Issue by dtaivpp** [opensearch-project/demos#67]
### Is your feature request related to a problem?
In our cluster bootstrap we will need to enable these two settings to build our pipelines. These should be put into `cluster_bootstrap.py:initialize_cluster_settings`  

- https://opensearch.org/docs/latest/ml-commons-plugin/conversational-search/#working-with-conversations-and-interactions
- https://opensearch.org/docs/latest/ml-commons-plugin/conversational-search/#enabling-rag

**Comment by LucasWang750** [comment]
I would like to work on this!

**Comment by dtaivpp** [comment]
Assigned!
