### ISSUE TITLE
[FEATURE][DocBot] Add method to create search pipeline

### ISSUE THREAD

**Issue by ortegaa32** [opensearch-project/demos#93]
### Is your feature request related to a problem?
We currently don't have a method to create a search pipeline so we can't complete the RAG pipeline.

### What solution would you like?
We can add a new method as part of the monkey patch in `util.py`

**Comment by ortegaa32** [comment]
Can I be assigned to this issue please?

**Comment by dtaivpp** [comment]
Assigned!

**Comment by dtaivpp** [comment]
Closed with #97
